### ISSUE TITLE
[OGRE-38] OgreXMLConverter assumes bone IDs from 0 to N-1 

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#11]
<b>[reporter="spacegaier", created="Sat, 24 Nov 2012 20:07:52 +0100"]</b>

<p>Original reporter: FuzzyBoots</p>

<p>Partially documented in forum topic <a href="http://www.ogre3d.org/forums/viewtopic.php?f=2&t=59825" class="external-link" rel="nofollow">http://www.ogre3d.org/forums/viewtopic.php?f=2&t=59825</a> <span class="error">&#91;^&#93;</span></p>

<p>When the OgreXMLConverter is reading in an XML Skeleton file, it assumes that the Bone IDs will go from 0 to N-1, storing them internally in an array indexed by the same. If, for example, the bone IDs are 1 to N, there will be a segmentation fault due to it trying to access a nonexistent record at index 0. Currently, the DTD spec marks the ID as required, but does not list the format needed (i.e. values should be from 0 to N-1).</p>

<p>My suggestion would be for the XML Converter to either support reading in arbitrary IDs that do not have to go from 0 to N-1, or to provide an error message if this sequence is not followed. </p>

<p><b>Original Mantis Ticket:</b> <a href="http://www.ogre3d.org/mantis/view.php?id=421" class="external-link" rel="nofollow">http://www.ogre3d.org/mantis/view.php?id=421</a></p>

**Comment by pedrocunial** [comment]
Hello @paroj I saw that this issue is tagged as solved in the forums, is this still relevant? I wanted to start contributing to your project and this seemed like a good starting point!

Cheers 🥂 !

**Comment by paroj** [comment]
no idea - that was reported before I joined the project. The first step would be creating a test case for this to see whether we can reproduce the issue.

**Comment by paroj** [comment]
yes, the issue still exists, see `SkeletonSerializer::writeSkeleton`
https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreSkeletonSerializer.cpp#L193
